global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'notification-api'
    static_configs:
      - targets: ['notification-api:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
